### ISSUE TITLE
Upgrade clients to Node 18 and upgrade packages

### ISSUE THREAD

**Issue by whusterj** [thinknimble/tn-spa-bootstrapper#122]
Our React and Vue apps currently use Node 14 and a corresponding NPM version. We should bump this up to something more recent like Node 18 and fix any corresponding package issues (node-sass usually has trouble with node version upgrades).

**Comment by oudeismetis** [comment]
**Update notes for this (still active) issue:**
Node 14 -> 16 happened in https://github.com/thinknimble/tn-spa-bootstrapper/pull/129
16 will hit end-of-life 09/2023
18 is the current recommendation, became LTS in 10/2022, and will be valid until 2025.

https://github.com/nodejs/release#release-schedule

**Comment by oudeismetis** [comment]
This was resolved months ago in the linked PR #224 . Closing this issue.
