### ISSUE TITLE
Use django-environ for environment variable validation and type-casting

### ISSUE THREAD

**Issue by whusterj** [thinknimble/tn-spa-bootstrapper#17]
See: https://github.com/joke2k/django-environ

This should simplify some of the common things we do in settings.py and help prevent dumb errors having to do with casting environment variable types from string to whatever else.

**Comment by oudeismetis** [comment]
Just revisiting this PR now as I was looking for things to cleanup.
https://github.com/thinknimble/tn-spa-bootstrapper/pull/60 actually implemented `python-decouple` which I believe address all the capabilities of this library.
Will leave this open for the moment to hear comments/opinions, but will likely close this issue soon.

**Comment by whusterj** [comment]
Yeah! I thought I put this somewhere...

I think decouple and environ are about equivalent. I think environ has a little bit more magic like `db_url` and `cache_url` helper functions to generate those configs for Django, but I don't think it's substantially different or better in any way. I'd be in favor of closing this issue as resolved.

**Comment by whusterj** [comment]
Closing - `python-decouple` does the trick.
