### ISSUE TITLE
Update Mobile Appstore deployment

### ISSUE THREAD

**Issue by paribaker** [thinknimble/tn-spa-bootstrapper#175]
Currently to build an appstore version you must - manually update the version number in the app.config.js, push to main, deploy each platform separately 
Change this to: 
- allow entering version number in workflow dispatch 
- this should create a new release branch and tag, auto approve and merge 
- Also allow selecting just one or both platforms in build

**Comment by whusterj** [comment]
@paribaker - I know we've done a lot of mobile work in the past year. So is this done?
