### ISSUE TITLE
Docker installs vue stuff when there's no Vue app

### ISSUE THREAD

**Issue by lakardion** [thinknimble/tn-spa-bootstrapper#179]
> RUN npm install @vue/cli@3.7.0 -g

Probably we can cookiecut this so that we just don't install Vue always

**Comment by NC-Fran** [comment]
I removed this line in this PR: https://github.com/thinknimble/tn-spa-bootstrapper/pull/195
This library is already included as a dev dependency in `package.json`, so now that the node_modules are being correctly installed, there's no need to install it separately.

Could you please validate it works fine?
