### ISSUE TITLE
Fix flake8 and black linting in generated projects

### ISSUE THREAD

**Issue by whusterj** [thinknimble/tn-spa-bootstrapper#18]
We have some pytest-cookies tests written for flake8 and black, but they are failing because the generated project is not compliant. Once we merge #12, we should quickly follow up with a PR fixing all the linting issues and then re-enable those tests.

**Comment by oudeismetis** [comment]
I think this issue should remain open until Github Actions (both generated project as well as the bootstrapper) run linters to confirm no regressions here. PRs to the bootstrapper should fail for linting issues.

(Thus running black and opening a PR that touches all the files is something we should only ever have do once)
