### ISSUE TITLE
Missing env var in .env.example

### ISSUE THREAD

**Issue by paribaker** [thinknimble/tn-spa-bootstrapper#186]
We recently added a new env var 
`ENABLE_EMAILS`

but did not include it in the .env.example, while it defaults to `False` its best to add it as an example to prompt users

https://github.com/thinknimble/tn-spa-bootstrapper/blob/ca60c3534a1480c8edc28835c0ed7a3d06942228/%7B%7Bcookiecutter.project_slug%7D%7D/.env.example#L138

**Comment by MatterAndy** [comment]
Hello. I just made PR #187 to resolve this issue. Hope this helps!

**Comment by oudeismetis** [comment]
Resolved in https://github.com/thinknimble/tn-spa-bootstrapper/pull/187
Thanks @MatterAndy !!
