### ISSUE TITLE
Implement an example of django admin filters

### ISSUE THREAD

**Issue by oudeismetis** [thinknimble/tn-spa-bootstrapper#198]
https://github.com/thinknimble/tn-spa-bootstrapper/pull/194 added a powerful django admin feature.
Like many features like this, there is a risk it'll never be used since the code is there but none of the out-of-the-box admin views have a filter applied.

Find (in appropriate) at least one sensible admin view that a project would have after bootstrapping that would benefit from this feature and implement it.
The feature will get a lot more use if there is a good example like that from day 1 of a project.

**Comment by franagustin** [comment]
Addressed in https://github.com/thinknimble/tn-spa-bootstrapper/pull/232
