### ISSUE TITLE
Fix client dependencies

### ISSUE THREAD

**Issue by villagrat** [thinknimble/tn-spa-bootstrapper#199]
https://github.com/thinknimble/tn-spa-bootstrapper/pull/196/ reorganizes the client side so that it aligns part of the web & mobile structure of the apps. It looks like it may be missing `zod` as a dependency, so we should add that to the client's `package.json`, bootstrap a client project and check that everything runs out-of-the-box.

Bonus points:
 - review if there are no similar missing dependencies on the mobile side of the bootstrapper

**Comment by Nkiriobasi** [comment]
if I may understand the issue, zod used but not installed as dependency in the client side, what I don't understand is bootstraping a client project. please assist.

**Comment by villagrat** [comment]
You are correct, zod is being used but not included in the package.json so the app crashes when running the client with `yarn start`. You can find info on how to bootstrap a project [on this quickstart guide](https://github.com/thinknimble/tn-spa-bootstrapper#quick-start)

**Comment by Nkiriobasi** [comment]
Alright, I am very clear on what is needed to be done. can I go ahead?

**Comment by villagrat** [comment]
@Nkiriobasi sure, go ahead! [Here you will find more details about how to contribute](https://github.com/thinknimble/tn-spa-bootstrapper/blob/main/CONTRIBUTING.md)
