### ISSUE TITLE
Remove GQL from react side 

### ISSUE THREAD

**Issue by paribaker** [thinknimble/tn-spa-bootstrapper#220]
We are temporarily removing GQL until we have enough catch up and a better integration strategy + experience etc

**Comment by lakardion** [comment]
+1.

Vue is not supporting gql, neither is react-native.

All the cookiecutter syntax also makes the DX pretty unpleasant. This removes any chance to do autoformatting or even developing directly in the bootstrapper, instead we need to cookiecut and create a whole new project work there and then replicate the changes in this repo.
