### ISSUE TITLE
Update Docker to 3.10

### ISSUE THREAD

**Issue by paribaker** [thinknimble/tn-spa-bootstrapper#237]
Currently the Docker is set to `python:3.7-slim-buster` this should change to `3.10`

https://hub.docker.com/layers/library/python/3.10-slim-buster/images/sha256-f1fe2cb1bee7a6cf3f9eaf07c7ef8b417cf2cf23a751d90f4e12d583c4a38e6e

Also need to add when using Docker
`vite/`

to the gitignore of the client dir

**Comment by oudeismetis** [comment]
fixed in https://github.com/thinknimble/tn-spa-bootstrapper/pull/229
