### ISSUE TITLE
Migrate E2E Tests from Cypress to Playwright

### ISSUE THREAD

**Issue by whusterj** [thinknimble/tn-spa-bootstrapper#330]
# TO DO

- [x] Migrate VueJS e2e tests from Cypress to Playwright
- [x] Migrate React e2e tests from Cypress to Playwright
- [x] All FEs should have sample e2e tests for login and account creation (from #55)

**Comment by lakardion** [comment]
FYI . Playwright is only for web. I couldn't find anything from them about react native.

**Comment by lakardion** [comment]
https://docs.expo.dev/build-reference/e2e-tests/

This is what the expo people mention. We had tried detox a long time ago and I think there was an attempt as well in one of our projects (C.C.?) Where @OkayItsMikael and @noriega2112 had given it a shot as well but I think there were some issues when they tried implementing e2e in RN

**Comment by whusterj** [comment]
I see. Thanks for sharing! For the purposes of this issue we can focus on just the web frameworks.

**Comment by whusterj** [comment]
In progress: #335

**Comment by whusterj** [comment]
Tests are failing on `main` - reopening until we sort that out.

cc: @noriega2112

**Comment by whusterj** [comment]
Got the tests passing. Migrations were not properly applied on staging. Handled that and made sure the playwright user exists on staging for future E2E tests.

This is good now!
