### ISSUE TITLE
add formation to app.json

### ISSUE THREAD

**Issue by paribaker** [thinknimble/tn-spa-bootstrapper#44]
Add [formation](https://devcenter.heroku.com/articles/app-json-schema#formation) to app.json so that it does not use whatever is already on prod/staging, 
```
  "formation": {
    "web": {
      "quantity": 1,
      "size": "free"
    }
  },
```

> You will incur billing charges for dynos used based on the formation requested.

**Comment by oudeismetis** [comment]
Not sure if still needed. New apps default to cheaper resources. Or is this an issue if prod is created before review apps with beefier machines?

**Comment by whusterj** [comment]
Stale - closing.
