### ISSUE TITLE
vue3 apiErrorHandler() fails to rethrow error if enable400Alert

### ISSUE THREAD

**Issue by brunogarciagonzalez** [thinknimble/tn-spa-bootstrapper#54]
In: `clients/vue3/services/api.js`

apiErrorHandler() fails to rethrow error if `enable400Alert` is set to `true`.

This is due to an early return that needs to be reworked.

**Comment by brunogarciagonzalez** [comment]
The vue3 bootstrapper code does not make user of `AlertAlert` but it does still make use of `apiErrorHandler()`, which leads to the need to answer the following question:
When the `apiErrorHandler` is to trigger a 400 or 500 -level alert, what should be triggered?
I could either bring back `AlertAlert` or wait until we decide on a design system for the vue3 client so that we leverage that for this scenario

**Comment by brunogarciagonzalez** [comment]
As per @whusterj 's recommendation, the goal is to bring `AlertAlert` back into the bootstrapper.

@paribaker is working on a vue3 version that would be compatible with the new vue3 client.

**Comment by oudeismetis** [comment]
@paribaker is there an update on this?

**Comment by whusterj** [comment]
Stale - closing.
