### ISSUE TITLE
Cypress test example for Vue

### ISSUE THREAD

**Issue by oudeismetis** [thinknimble/tn-spa-bootstrapper#55]
Login and account creation now exist, so we should add Cypress test support with one or two thoughtful test examples.
For simplicity, Cypress should point at the Heroku Review App for a PR and should point to Staging when it is run against the main branch.

**Comment by oudeismetis** [comment]
These tests are for the generated project, but should be run on bootstrapper PRs as well (if we can) to validate that new bootstrapper changes don't break functionality in the generated apps.

**Comment by oudeismetis** [comment]
Partially completed. There is a test for login but account creation isn't tested.
These tested could also be a little more verbose to serve as a good example for other devs

**Comment by whusterj** [comment]
We're migrating to Playwright, so I will make this a to-do of #330
