### ISSUE TITLE
Move the `send_html_email` function somewhere more visible

### ISSUE THREAD

**Issue by whusterj** [thinknimble/tn-spa-bootstrapper#62]
I noticed that `send_html_email` is in the utils/misc.py file. I think that may lower awareness of this function too much, when we really should try to raise awareness of it. IMO, it's really, really useful and should be our default way of sending emails - everyone expects HTML emails these days. I'd recommend at least moving it to utils/emails.py or maybe even into the core Django app so it's more readily visible.

Open to suggestions. Maybe Django has a better built-in email sender nowadays?

**Comment by eschwartz929** [comment]
Addressed in PR 76 https://github.com/thinknimble/tn-spa-bootstrapper/pull/76

**Comment by oudeismetis** [comment]
This has been fixed. closing issue now.
