### ISSUE TITLE
Add documentation for needed docker steps when new python pkgs in Pipfile

### ISSUE THREAD

**Issue by brunogarciagonzalez** [thinknimble/tn-spa-bootstrapper#80]

**Comment by oudeismetis** [comment]
Closing this issue as I'm not exactly sure what to improve here.
Adding to the pipfile will carry over into Docker when docker is asked to build again.
I guess right now you just need to know that when you change the pipfile you need to do that step. But the same would be true outside of docker where you'd have to update your venv.
