### ISSUE TITLE
Support No Backend Opts

### ISSUE THREAD

**Issue by paribaker** [thinknimble/tn-spa-bootstrapper#9]
I tried to start a project but did not want a backend I figured I could just delete it after it was generated however when I was going through the steps I did not select a provider for static files so it failed 

> ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully

Maybe either add selection for no backend or set one by default if non are selected.

**Comment by whusterj** [comment]
Closing, b/c stale.
